services:
  handyman:
    - localhost:9070
  rancher:
    - localhost:9090
# TODO link with docker containers

spring:
  datasource:
    url: jdbc:postgresql://localhost:30240/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/db.changelog-master.yaml