version: '3.8'

networks:
  monitoring:
    driver: bridge

# TODO link with docker containers
services:
  handyman-service:
    image: handyman-service
    container_name: plaintit-handyman-service
    ports:
      - "8070:8070"
      - "9070:9070"
    networks:
      - monitoring
  landscape-service:
    image: landscape-service
    container_name: plaintit-landscape-service
    ports:
      - "8080:8080"
    networks:
      - monitoring
  rancher-service:
    image: rancher-service
    container_name: plaintit-rancher-service
    ports:
      - "8090:8090"
      - "9090:9090"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: plaintit-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: plaintit-grafana
    ports:
      - "9095:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring
  postgres:
    image: postgres:latest
    container_name: plaintit-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
