FROM gradle:jdk19 as BUILD_IMAGE

WORKDIR /plantit/gradle

 COPY ./common-grpc-connectivity ./common-grpc-connectivity
COPY ./handyman-service ./handyman-service

WORKDIR /plantit/gradle/handyman-service

RUN gradle build


FROM openjdk:19

ENV APP_HOME /plantit/app
ARG APP_VERSION="SNAPSHOT"
ARG APP_PORTS="8070 9070"

WORKDIR $APP_HOME

COPY --from=BUILD_IMAGE /plantit/gradle/handyman-service/build/libs/handyman-service-$APP_VERSION.jar app.jar
EXPOSE $APP_PORTS

CMD ["java","-jar","app.jar"]