FROM gradle:jdk19 as BUILD_IMAGE

WORKDIR /plantit/gradle

COPY ./handyman-service ./handyman-service

COPY ./common-grpc-connectivity ./common-grpc-connectivity

WORKDIR /plantit/gradle/handyman-service

RUN gradle build


FROM openjdk:jdk19

WORKDIR /plantit/app

COPY --from=BUILD_IMAGE /plantit/gradle/handyman-service/build/libs/handyman-service-0.0.2-SNAPSHOT.jar .

EXPOSE 8080

CMD ["java","-jar","handyman-service-0.0.2-SNAPSHOT.jar"]